# Generated by Django 3.2.7 on 2021-10-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_individuo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
