# Generated by Django 3.2.7 on 2021-10-16 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_individuo_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('state', models.BooleanField()),
                ('entity', models.CharField(max_length=200)),
                ('howmuch', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=300, null=True)),
                ('active', models.BooleanField()),
                ('views', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
