# Generated by Django 3.2.7 on 2021-10-17 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(blank=True, null=True)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('indiv_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indiv_afil', to='app.individuo')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_afil', to='app.partido')),
            ],
        ),
    ]
