# Generated by Django 3.2.7 on 2021-10-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_afiliacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliacion',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
