# Generated by Django 3.2.7 on 2021-11-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_afiliacion_date_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_imp', models.DateField(blank=True, null=True)),
                ('charges', models.DateField(blank=True, null=True)),
                ('guilty', models.BooleanField(null=True)),
                ('sentence', models.CharField(max_length=45, null=True)),
                ('commnts', models.CharField(max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indiv_impl', to='app.afiliacion')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proceso_impl', to='app.proceso')),
            ],
        ),
    ]
