# Generated by Django 3.2.7 on 2021-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_afiliacion_date_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliacion',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
